### ISSUE TITLE
Amazon - the number of jobs posted on Peviitor isn't the same as the one returned by the API

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scraper_Api#11]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Amazon" in the search bar.
3. Check the number of jobs available for Amazon.
4. Run "Amazon" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_py/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 26 while the number of jobs returned by the API is 203.

![Amazon peviitor](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/b3ac27d2-3095-4d4c-98ed-72810a70b90f)

![amazon scraper](https://github.com/peviitor-ro/based_scraper_py/assets/134513404/36873cdb-319f-4632-b941-828e0ecb556c)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting the number of jobs posted on peviitor.ro is the same as the one returned by the API

![Image](https://github.com/peviitor-ro/scraper_Api/assets/72222644/1ab2e04a-a858-4e65-9ce0-9a5016268099)
