### ISSUE TITLE
Freudenberg - The number of jobs posted on Peviitor and the one returned by the API isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scraper_Api#12]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Freudenberg" in the search bar.
3. Check the number of jobs available for Freudenberg.
4. Run "Freudenberg" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_py/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 9 while the number of jobs returned by the API is 11.

![freudenberg peviitor](https://github.com/peviitor-ro/scraper_Api/assets/134513404/a0594ad9-776e-48ba-8823-2970acad6d21)

![freudenberg scraper](https://github.com/peviitor-ro/scraper_Api/assets/134513404/e91e7f38-94ba-480b-8006-23fa8dcb9bb5)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting the number of jobs posted on peviitor and the one returned by the API are the same (15)

![Image](https://github.com/peviitor-ro/scraper_Api/assets/72222644/5068f5ba-18f0-485b-8ec3-3aa214898b14)
