### ISSUE TITLE
Synevo - The number of jobs posted on Peviitor  and the one returned by the API isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scraper_Api#16]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Synevo" in the search bar.
3. Check the number of jobs available for Synevo.
4. Run "Synevo" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_py/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 14 while the number of jobs returned by the API is 27.

![synevo peviitor](https://github.com/peviitor-ro/scraper_Api/assets/134513404/5f74d39c-a840-4839-ae0a-3df1fe460484)

![synevo scraper](https://github.com/peviitor-ro/scraper_Api/assets/134513404/9cf79fe2-1782-4ed5-b7aa-4d82f93b0733)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting, the number of jobs posted on the peviitor and the number of jobs returned by the API is the same. (17)

![Image](https://github.com/peviitor-ro/scraper_Api/assets/72222644/c83e42dc-00fc-4ee3-beb8-6b52540d5476)
