### ISSUE TITLE
GoodYear - The number of jobs posted on Peviitor (25) and the one returned by the API (50) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scraper_Api#17]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "GoodYear" in the search bar.
3. Check the number of jobs available for GoodYear.
4. Run "GoodYear" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_py/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 25 while the number of jobs returned by the API is 50.

![good year peviitor](https://github.com/peviitor-ro/scraper_Api/assets/134513404/580955a4-fdba-4a15-9997-6d8a16a6b861)

![good year scraper](https://github.com/peviitor-ro/scraper_Api/assets/134513404/9a610d6c-b65d-4e57-955a-f9b7527c8437)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting, the number of jobs posted on the peviitor and the number of jobs returned by the API is the same.(77)


![Image](https://github.com/peviitor-ro/scraper_Api/assets/72222644/09dbec6d-3ab1-4a62-bd5a-be80dadfdf50)
