### ISSUE TITLE
Renault - The number of jobs posted on Peviitor (143) and the one returned by the API (1123) isn't the same.

### ISSUE THREAD

**Issue by Ale230992** [peviitor-ro/scraper_Api#18]
ENVIROMENT: production
URL: https://peviitor.ro/
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open "https://peviitor.ro/" in the browser.
2. Type "Renault" in the search bar.
3. Check the number of jobs available for Renault.
4. Run "Renault" scraper on "https://dev.laurentiumarian.ro/scraper/based_scraper_py/".
5. Check the number of jobs displayed.

EXPECTED RESULTS:
The number of jobs posted on "https://peviitor.ro/" and the number of jobs returned by the API should be the same.

ACTUAL RESULT:
The number of jobs posted on Peviitor website is 143 while the number of jobs returned by the API is 1123.

![renault peviitor](https://github.com/peviitor-ro/scraper_Api/assets/134513404/58a6fc5a-0261-4716-8a53-9564d9c28785)

![renault scraper](https://github.com/peviitor-ro/scraper_Api/assets/134513404/9d4810eb-b8ba-4128-b8bf-07b27af43f2b)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdiVanca** [comment]
After retesting, the number of jobs posted on the peviitor and the number of jobs returned by the API is the same.(58)


![Image](https://github.com/peviitor-ro/scraper_Api/assets/72222644/48971cac-66cf-48b9-81e2-eb2914b78f50)
