### ISSUE TITLE
Amazon - The jobs on the "peviitor Scrapers API V1" do not all appear in "solr.peviitor" 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scraper_Api#27]
ENVIRONMENT: production
URL: https://solr.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1. Open the URL in the browser
  2. Go to "Amazon" company and check the number of jobs
  3. Open https://dev.laurentiumarian.ro/scraper/based_scraper_py
  4. Check if the number of jobs for the Amazon company  is the same as the number of jobs on solr.peviitor.ro

EXPECTED RESULTS:
The number of jobs is the same

ACTUAL RESULTS:
The number of jobs is higher on Scrapers API V1 than on solr.peviitor.ro

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, the number of jobs is the same on solr.peviitor.ro as on the scrapers.peviitor.ro


![Image](https://github.com/peviitor-ro/scraper_Api/assets/122023703/f37e2823-c473-4547-8be6-aa9392d8c8b8)



![Image](https://github.com/peviitor-ro/scraper_Api/assets/122023703/1e28e70a-bfc7-416d-9134-cea7bab0d0d6)
