### ISSUE TITLE
Missing city - Amazon - Brand Specialist/Account Manager Italian - Remote 

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scraper_Api#28]
ENVIRONMENT: production
URL: https://dev.laurentiumarian.ro/scraper/based_scraper_py
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

  1.  Open the URL in the browser
  2.  Go to "Amazon - Brand Specialist/Account Manager Italian - Remote 
  3.  Check the city
  
 EXPECTED RESULTS:
The city is passed correctly

ACTUAL RESULTS:
No City on  peviitor Scrapers API V1
Instead of the city it is "null"

![image](https://github.com/peviitor-ro/scraper_Api/assets/122023703/fada9d28-b54d-4228-902b-a9300f97e0cf)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by AdrianaCionca** [comment]
After retesting, the job "Brand Specialist/Account Manager Italian - Remote" is no longer part of Amazon's job offer and all other active jobs have a city as their location.



![Image](https://github.com/peviitor-ro/scraper_Api/assets/122023703/ff294b6a-9223-4f48-a4b5-8fe0584b40e5)
