### ISSUE TITLE
Hrsromania - Inactiv status

### ISSUE THREAD

**Issue by LarisaM16** [peviitor-ro/scraper_Api#36]
ENVIRONMENT: PROD
URL: https://firme.peviitor.ro/
browser: Chrome/ Firefox/ Microsoft Edge

STEPS TO REPRODUCE:

1. open url in the browser
2. type Hrsromania in the search bar
3. click on the Hrsromania 
4. click on Run Scraper
5. check the status

EXPECTED RESULTS:
Status is active

ACTUAL RESULTS:
Status Inactiv  is displayed
![Screenshot_66](https://github.com/peviitor-ro/scraper_Api/assets/124587607/b9c95334-e1ff-4a18-a637-ac2b4fda9525)

**Comment by lalalaurentiu** [comment]
Nu este Api ul de vina , trebuie sters acel “list[dict]” de la sfârșitul Declarației metodei
![IMG_4067](https://github.com/peviitor-ro/scraper_Api/assets/67306273/038169a9-5e3c-4f4f-9d2a-2bf3f554be75)

**Comment by melania23m** [comment]
Fixed! Thank you @lalalaurentiu

**Comment by LarisaM16** [comment]
Now is activ.
