### ISSUE TITLE
Unilever - Missing Location and Job type for the job "Area Sales Manager West Romania"

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/scraper_Api#38]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run Scraper for "Unilever" Company
3. Check the location and job type for the "Area Sales Manager West Romania" job
4. Open "Vezi Postul" and check the location and job type for the "Area Sales Manager West Romania" job

EXPECTED RESULTS:
The Job type is "Remote" as on the company website

ACTUAL RESULTS:
Missing Location and Job Type for the job "Area Sales Manager West Romania"
On http://solr.peviitor.ro/ the city and county of the job is "false" instead of "Bucharest" as on the company's website

![image](https://github.com/peviitor-ro/scraper_Api/assets/122023703/025a64c1-05dd-41e9-a02a-17accd8b4a99)

![image](https://github.com/peviitor-ro/scraper_Api/assets/122023703/80d6ce12-220d-4b0b-ac0b-3ea9a9aca197)
![image](https://github.com/peviitor-ro/scraper_Api/assets/122023703/86234fe0-738e-48f9-a725-93212c9fb34d)

**Comment by lalalaurentiu** [comment]
Deprecated....
